### ISSUE TITLE
Game Keeps Crashing Every Time I Die

### ISSUE THREAD

**Issue by Samster1471** [gb2dev/HLA-NoVR#249] opened 2024-07-10 16:17 UTC
I don't have VR and downloaded this mod to play the game. At first, it worked well, but as I progressed later on in the game, it started to crash whenever I died. Now, it happens every single time I die. I don't know whether this is a problem with the mod or the game, but it is intensely irritating.

System Specs:
----------------------
Asus TUF Gaming A15
500 GB storage
16GB RAM
Nvidia Geforce RTX 4060

**Comment by gb2dev** [comment] 2024-07-11 11:40
Duplicate of #197

**Closed by gb2dev** 2024-07-11 11:40 UTC
