### ISSUE TITLE
Game crashes every time I die.

### ISSUE THREAD

**Issue by fnavas00** [gb2dev/HLA-NoVR#250] opened 2024-07-15 23:34 UTC
Hello Im not sure if this has been reported before but the game will crash anytime I die. Im at the exterior courtyard level the game continues crashing anytime I die making it very unplayable

**Comment by Turker13** [comment] 2024-07-29 17:48
Hi. I also have this exact problem.

**Comment by gb2dev** [comment] 2024-08-04 11:51
Duplicate of #197

**Closed by gb2dev** 2024-08-04 11:51 UTC
