### ISSUE TITLE
Main Menu Not Loading In Title Space

### ISSUE THREAD

**Issue by godsSide** [gb2dev/HLA-NoVR#281] opened 2024-12-28 17:37 UTC
Greetings, I can load into the mod and the intro cutscenes will play but I get stuck at the "Half-Life: Alyx" text without anything loading afterwards in the 3D title space. I've tried uninstalling and reinstalling the game and the mod but it keeps repeating the same problem. I am stuck in the 3D Title Space. I can look around with my arrow keys, I can press M to restart the title space. My game loads the main menu title delay 999999 does this have something to do with it? I've tried messing around in the console and if I set those values to 0 the menu pops up but its the VR menu, not the mod. Please help.

**Comment by godsSide** [comment] 2024-12-28 22:08
I had uninstalled the game and reinstalled it along with the mod. It works on the initial load but subsequent loads still present the issue.

**Comment by gb2dev** [comment] 2024-12-30 13:07
Duplicate of #276

**Closed by gb2dev** 2024-12-30 13:07 UTC
